#+TITLE: Parser
#+DATE: 2026-10-09
#+FILETAGS: :design:
#+DESCRIPTION: Explaining the how and the why of our parser.
#+KANA: よみ
#+OPTIONS: toc:nil title:nil

* Strategy

We parse the Karuta code using a hand-written [[https://en.wikipedia.org/wiki/Recursive_descent_parser][recursive-descent parser]]. The implementation
is based on a grammar written using the [[https://bford.info/pub/lang/peg.pdf][PEG]] formalism, but since we factor out some common structures into
high-level helper functions we end up with a flavor of [[https://en.wikipedia.org/wiki/Parser_combinator][parser combinators]]. While some of those helper functions
behave like PEG primitives, others are in fact syntactic sugar and should be thought of as a layer of macros on top of the base PEG semantics.
As a side note, the entire parser is pedantic about [[https://en.wikisource.org/wiki/Lambda:_The_Ultimate_GOTO][proper tail-calls]]; we use OCaml's proper tail-calls
in such a way that any parsing expression which would be in tail position in the grammar is in fact a tail-call in OCaml.

The parser is written in a [[https://en.wikipedia.org/wiki/Monad_(functional_programming)][monadic style]]: a parser is a function taking a parser state and returning either a parse result together with
the next parser state, or an error. [[https://en.wikipedia.org/wiki/Applicative_functor][Applicative-style]] operators could be derived from the monadic ones, but we don't currently use this approach.

#+BEGIN_SRC ocaml
type ('a, 'e) parser = parser_state -> ('a * parser_state, 'e) result
#+END_SRC

The full code of the parser is located in ~lib/Parser.ml~.

* Disclaimer

We recognize that our syntax errors are /bad/, i.e., our parser does not take into consideration the *semantics* of the language, which leads to
frustrating error messages in most situations. For example, pretty much /everything/ in our language is a functor (in the Prolog sense, not
the ML sense), and we parse it as such. Any syntax error will therefore note take into account /what you are trying to do/.

We do intend to improve our error messages, but we have other priorities right now. Contributions on this front are welcome.

* Types

** Source Code Location

Because Karuta's compiler needs to report intelligible error messages with source code location, our parser
leverages a type which is an alias for the type ~Lexing.position~ provided in the standard library
[[https://ocaml.org/manual/5.4/api/Lexing.html][Lexing module]], located in ~Location~ module:

#+BEGIN_SRC ocaml
type t = Lexing.position
(** Alias to standard library's Lexing.position type. Our type has the same
    fields as the original ones, which have the following description (official
    documentation):

    pos_fname is the file name; pos_lnum is the line number; pos_bol is the
    offset of the beginning of the line (number of characters between the
    beginning of the lexbuf and the beginning of the line); pos_cnum is the
    offset of the position (number of characters between the beginning of the
    lexbuf and the position). The difference between pos_cnum and pos_bol is the
    character offset within the line (i.e. the column number, assuming each
    character is one column wide). *)
#+END_SRC

This type is used to save half of the full location information. In order to save the /entire/ location, i.e., where it begins
and where it ends, we use the following type everywhere in the code base:

#+BEGIN_SRC ocaml
type location = {
  startl : t;  (** Beginning of region *)
  endl : t;  (** End of region *)
}
(** Source code location. Locations delimit a source code region. *)
#+END_SRC

In the future, we have interest on embedding the source filename into this type as well.
You can attach a location to an arbitrary type with the following type:

#+BEGIN_SRC ocaml
type 'a with_location = {
  content : 'a;  (** Generic type payload *)
  loc : location;  (** Associated location, with a beginning and end. *)
}
(** Parametric type to add a location to any other type. Used to indicate the
    source code region where the payload originated. *)
#+END_SRC

Our parser uses several helper functions to manipulate the location more conveniently:

#+BEGIN_SRC ocaml
let step n loc = { loc with pos_cnum = loc.pos_cnum + n }

let jump loc = { loc with pos_bol = loc.pos_cnum; pos_lnum = loc.pos_lnum + 1 }

let jump_n n loc =
  if n = 0 then loc
  else { loc with pos_bol = loc.pos_cnum; pos_lnum = loc.pos_lnum + n }

let plus_str str loc =
  step (String.length str) loc
  |> jump_n
       (String.fold_left (fun n -> function '\n' -> n + 1 | _ -> n) 0 str)
#+END_SRC

We elided the comments to save space; you can read them on the source code for more details.

** Parsing

There are two main types used in the act of parsing. Let's start with ~parser_state~:

#+BEGIN_SRC ocaml
type parser_state = { remaining : BatSubstring.t; loc : Location.t }
#+END_SRC

The type ~parser_state~ holds the bookkeeping required to parse source files. ~remaining~ is the portion of the source file that we haven't parsed yet,
represented as a ~BatSubstring.t~ (so we have constant-time slicing).
~loc~ is the (half) location (~Location.t~) representing the point in the file where the parser state is currently at.

#+BEGIN_SRC ocaml
type ('a, 'e) parser = parser_state -> ('a * parser_state, 'e) result
#+END_SRC

The type ~parser_state~ is a [[https://en.wikipedia.org/wiki/Monad_(functional_programming)][Monad]].
In particular, it can be seen as a composition of the [[https://wiki.haskell.org/State_Monad][state]] monad with the [[https://en.wikipedia.org/wiki/Result_type][either/result]] monad.

The entry point of the parser is the function ~Parser.parse~, which corresponds in the grammar to the ~start~ symbol.

* Grammar

This is the complete formal grammar for the language. In the source code, you'll find the functions implementing each
grammar clause commented with the corresponding clause, but you can read it here in one place.

#+BEGIN_SRC peg
start <- top_level !.
top_level <- whitespace_and_comments (clause whitespace_and_comments)*

clause <-
  holds whitespace_and_comments directive
  / !holds func whitespace_and_comments
    (&(question_mark / comma) query /
     !(question_mark / comma) declaration)
    whitespace_and_comments

query <-
  question_mark
  / !question_mark whitespace_and_comments comma
    whitespace_and_comments func whitespace_and_comments query

declaration <- (holds whitespace_and_comments declaration_body)?
  whitespace_and_comments period

declaration_body <- func whitespace_and_comments
  (comma whitespace_and_comments declaration_body / !comma)

directive <- func
 (whitespace_and_comments
  left_curly_brace top_level right_curly_brace
  whitespace_and_comments)*
 period whitespace_and_comments

expr <- whitespace_and_comments
  (integer
   / !integer (variable
               / !variable (func
                            / !func list)))

func <- func_label
 ((&left_bracket / &left_paren) (prolog_elements / karuta_elements)
  / !(&left_bracket / &left_paren))

func_label <- (atom colon)* (quoted_atom / atom)

atom <- [a-z] ([a-zA-Z0-9] / '_' / '-')*
variable <- ('_' / [A-Z]) ([a-zA-Z0-9] / '_')*
quoted_atom <- "'" (!"'" !'\n' .)* "'"

integer <- '-'? [0-9]+

list <- left_bracket whitespace_and_comments
  (right_bracket
   / !right_bracket expr whitespace_and_comments list_tail)

list_tail <-
  comma whitespace_and_comments expr whitespace_and_comments list_tail
  / !comma (pipe whitespace_and_comments expr)? whitespace_and_comments right_bracket

single_element <- whitespace_and_comments expr

karuta_elements <- left_bracket
  (whitespace_and_comments right_bracket /
   !(whitespace_and_comments right_bracket single_element) karuta_elements_loop)

karuta_elements_loop <-
  whitespace_and_comments comma expr karuta_elements_loop
  / !(whitespace_and_comments comma expr)
    whitespace_and_comments right_bracket

prolog_elements <- left_paren
  (whitespace_and_comments right_paren /
   !(whitespace_and_comments right_paren) single_element prolog_elements_loop)

prolog_elements_loop <-
  whitespace_and_comments comma expr prolog_elements_loop
  / !(whitespace_and_comments comma expr)
    whitespace_and_comments right_paren

whitespace_and_comments <- whitespace
  (percent line whitespace_and_comments
   / !percent (hash percent expr whitespace_and_comments
               / !(hash percent)))

whitespace <- horizontal_whitespace? (newline whitespace / !newline)

newline <- '\n' / '\r\n'
line <- newline / (. line / !.)

horizontal_whitespace <- (' ' / '\t')+

colon <- ':'
percent <- '%'
hash <- '#'
single_quote <- "'"
comma <- ','
period <- '.'
pipe <- '|'
question_mark <- '?'
left_paren <- '('
right_paren <- ')'
left_bracket <- '['
right_bracket <- ']'
left_curly_brace <- '{'
right_curly_brace <- '}'
holds <- ':-'
#+END_SRC